<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'To Kill a Mockingbird',
                'author'          => 'Harper Lee',
                'isbn'            => '978-0-06-112008-4',
                'genre'           => 'fiction',
                'description'     => 'A gripping tale of racial injustice and childhood innocence set in the American South during the 1930s, narrated by young Scout Finch.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg',
                'stock_total'     => 7,
                'stock_available' => 7,
                'price_per_day'   => 5000.00,
                'published_year'  => 1960,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => '1984',
                'author'          => 'George Orwell',
                'isbn'            => '978-0-45-228285-3',
                'genre'           => 'fiction',
                'description'     => 'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism, extreme political ideology, and mass surveillance.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780452282858-L.jpg',
                'stock_total'     => 10,
                'stock_available' => 10,
                'price_per_day'   => 5500.00,
                'published_year'  => 1949,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'Sapiens: A Brief History of Humankind',
                'author'          => 'Yuval Noah Harari',
                'isbn'            => '978-0-06-231609-7',
                'genre'           => 'non-fiction',
                'description'     => 'A sweeping narrative of humanity\'s creation and evolution that explores how biology and history have defined us and enhanced our understanding of what it means to be human.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
                'stock_total'     => 8,
                'stock_available' => 8,
                'price_per_day'   => 8000.00,
                'published_year'  => 2011,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'A Brief History of Time',
                'author'          => 'Stephen Hawking',
                'isbn'            => '978-0-55-305340-1',
                'genre'           => 'science',
                'description'     => 'A landmark volume in science writing that covers the origin and fate of the universe, black holes, the Big Bang, and the nature of time itself.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780553053401-L.jpg',
                'stock_total'     => 5,
                'stock_available' => 5,
                'price_per_day'   => 7500.00,
                'published_year'  => 1988,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'Guns, Germs, and Steel',
                'author'          => 'Jared Diamond',
                'isbn'            => '978-0-39-331755-8',
                'genre'           => 'history',
                'description'     => 'A Pulitzer Prize-winning analysis of why some civilizations came to dominate others, examining the environmental and geographical factors that shaped human history.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg',
                'stock_total'     => 6,
                'stock_available' => 6,
                'price_per_day'   => 9000.00,
                'published_year'  => 1997,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'The Hobbit',
                'author'          => 'J.R.R. Tolkien',
                'isbn'            => '978-0-54-792822-7',
                'genre'           => 'fantasy',
                'description'     => 'The beloved prequel to The Lord of the Rings trilogy, following the journey of Bilbo Baggins who is swept into an epic quest to reclaim the dwarves\' mountain home from a dragon.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg',
                'stock_total'     => 9,
                'stock_available' => 9,
                'price_per_day'   => 6000.00,
                'published_year'  => 1937,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'Clean Code: A Handbook of Agile Software Craftsmanship',
                'author'          => 'Robert C. Martin',
                'isbn'            => '978-0-13-235088-4',
                'genre'           => 'technology',
                'description'     => 'A revolutionary paradigm offering a practical guide to clean code, covering object-oriented design, refactoring, unit testing, and professional practices for software development.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
                'stock_total'     => 4,
                'stock_available' => 4,
                'price_per_day'   => 12000.00,
                'published_year'  => 2008,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'The Origin of Species',
                'author'          => 'Charles Darwin',
                'isbn'            => '978-0-14-043205-3',
                'genre'           => 'science',
                'description'     => 'Darwin\'s groundbreaking work introducing the theory of evolution through natural selection, fundamentally changing the way humanity understands life on Earth.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780140432053-L.jpg',
                'stock_total'     => 3,
                'stock_available' => 3,
                'price_per_day'   => 6500.00,
                'published_year'  => 1859,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'The Name of the Wind',
                'author'          => 'Patrick Rothfuss',
                'isbn'            => '978-0-75-640407-1',
                'genre'           => 'fantasy',
                'description'     => 'The riveting first-person narrative of Kvothe, a magically gifted young man who grows to be the most notorious wizard his world has ever seen.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780756404079-L.jpg',
                'stock_total'     => 6,
                'stock_available' => 6,
                'price_per_day'   => 7000.00,
                'published_year'  => 2007,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'Educated',
                'author'          => 'Tara Westover',
                'isbn'            => '978-0-39-959050-4',
                'genre'           => 'non-fiction',
                'description'     => 'A memoir about a young woman raised by survivalist parents in the mountains of Idaho who eventually escapes to learn about the wider world through self-education, ultimately earning a PhD from Cambridge University.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg',
                'stock_total'     => 5,
                'stock_available' => 5,
                'price_per_day'   => 8500.00,
                'published_year'  => 2018,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'Homo Deus: A Brief History of Tomorrow',
                'author'          => 'Yuval Noah Harari',
                'isbn'            => '978-0-06-246431-6',
                'genre'           => 'non-fiction',
                'description'     => 'A provocative exploration of humanity\'s future, examining how artificial intelligence, biotechnology, and data science may transform our world and redefine what it means to be human.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg',
                'stock_total'     => 7,
                'stock_available' => 7,
                'price_per_day'   => 9500.00,
                'published_year'  => 2015,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'The Design of Everyday Things',
                'author'          => 'Don Norman',
                'isbn'            => '978-0-46-506710-7',
                'genre'           => 'technology',
                'description'     => 'A compelling introduction to the principles of good design, explaining why some products satisfy customers while others frustrate them, covering human-centered design concepts.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780465067107-L.jpg',
                'stock_total'     => 4,
                'stock_available' => 4,
                'price_per_day'   => 11000.00,
                'published_year'  => 1988,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'Sapiens: Grafik Novel',
                'author'          => 'Yuval Noah Harari & David Vandermeulen',
                'isbn'            => '978-1-52-470451-5',
                'genre'           => 'history',
                'description'     => 'A richly illustrated graphic adaptation of the globally acclaimed Sapiens, tracing the history of humankind from the Stone Age through to the 21st century.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9781524704515-L.jpg',
                'stock_total'     => 8,
                'stock_available' => 8,
                'price_per_day'   => 10000.00,
                'published_year'  => 2020,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'The Great Gatsby',
                'author'          => 'F. Scott Fitzgerald',
                'isbn'            => '978-0-74-327356-5',
                'genre'           => 'fiction',
                'description'     => 'A masterpiece of twentieth-century literature set in the Jazz Age, exploring themes of decadence, idealism, resistance to change, social upheaval, and excess.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg',
                'stock_total'     => 10,
                'stock_available' => 10,
                'price_per_day'   => 4500.00,
                'published_year'  => 1925,
            ],
            [
                'id'              => (string) Str::uuid(),
                'title'           => 'The Pragmatic Programmer',
                'author'          => 'David Thomas & Andrew Hunt',
                'isbn'            => '978-0-13-595705-9',
                'genre'           => 'technology',
                'description'     => 'A classic guide to software development covering topics from personal responsibility and career development to architectural techniques, all aimed at making you a better programmer.',
                'cover_image_url' => 'https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg',
                'stock_total'     => 5,
                'stock_available' => 5,
                'price_per_day'   => 13000.00,
                'published_year'  => 2019,
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
