services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  user-service:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DB_CONNECTION: mysql
      DB_HOST: user-db
      DB_PORT: 3306
      DB_DATABASE: users_db
      DB_USERNAME: rent
      DB_PASSWORD: rent_password

      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

    ports:
      - "8001:8001"

    depends_on:
    - user-db
    - redis

  user-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: rent
      MYSQL_PASSWORD: rent_password
      MYSQL_ROOT_PASSWORD: root

volumes:
  user-db-data:
