services:
  notification-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notification_db
      MYSQL_USER: notification_user
      MYSQL_PASSWORD: notification_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  notification-service:
    depends_on:
      notification-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: Notification Service
      APP_ENV: local
      APP_PORT: 8004
      SERVICE_KEY: 2f3b9986e5cd631b726f80faa1ccbb8c8f404132a42fb41dc36ad9a45a1290a4
      DB_HOST: notification-db
      DB_PORT: 3306
      DB_DATABASE: notification_db
      DB_USERNAME: notification_user
      DB_PASSWORD: notification_password
    ports:
      - "8004:8004"
